# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode11.0

# IMPORTANT: xctool that Travis uses by default is not working so we need to run custom xcodebuild instead. Therefore, following default configurations are not applied.
# xcode_project: FlexColorPickerDemo/FlexColorPickerDemo.xcodeproj
# xcode_scheme: FlexColorPickerDemo
# xcode_sdk: iphonesimulator11.3

# cache: cocoapods
# we need to run pod install because podfile.lock is not in the repository
podfile: FlexColorPickerDemo/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=FlexColorPickerDemo

# Add -tc to xcpretty for no printout at all
script:
 - set -o pipefail && xcodebuild -workspace FlexColorPickerDemo/FlexColorPickerDemo.xcworkspace -scheme FlexColorPickerDemo -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO clean build | xcpretty
 - pod lib lint
